language: node_js #设置语言

node_js: v11.14.0  # 设置版本

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

before_install:
  - export TZ='Asia/Shanghai'  #更改时区

install:
  - npm install  # 安装hexo及插件

script:
  - hexo clean
  - hexo g

after_script:
  # clone Github Pages
  - rm -rf .deploy_git
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ..
  - mv .deploy_git/.git public/
  - cd public
  # push Github Pages
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GITHUB}@${GH_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Tagged by TravisCI with Build $TRAVIS_BUILD_NUMBER"
  - git push --quiet "https://${GITHUB}@${GH_REF}" master:master --tags
  # clone Coding Pages
  - rm -rf .git
  - cd ..
  - rm -rf .deploy_git
  - git clone https://${CODING_USER}:${CODING_PASS}@${CO_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ..
  - mv .deploy_git/.git public/
  - cd public
  # Coding Pages
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${CODING_USER}:${CODING_PASS}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Tagged by TravisCI with Build $TRAVIS_BUILD_NUMBER"
  - git push --quiet "https://${CODING_USER}:${CODING_PASS}@${CO_REF}" master:master --tags

branches:
  only:
    blog-source

env:
  global:
    # Github Pages
    - GH_REF: github.com/huangz986/huangz986.github.io.git
    # Coding Pages
    - CO_REF: git.dev.tencent.com/huangz986/huangz986.coding.me.git

notifications:
  email:
    - huangz986@bandingyun.com
  on_sucess: change
  on_failure: always
